#!/bin/sh


export ANDROID_SDK_HOME="/home/michael/Android/Sdk"
export ANDROID_NDK_API_LEVEL=21
export ANDROID_SDK_VERSION=21
export ANDROID_API_LEVEL=21
export ANDROID_BUILD_TOOLS_VERSION=33.0.0
export ANDROID_NDK_HOME="$ANDROID_SDK_HOME/ndk/21.4.7075529"
export ANDROID_HOME="$ANDROID_SDK_HOME/build-tools/21.1.2"
