#!/bin/sh

export PROJECT_ROOT="$HOME/AndroidStudioProjects/WhisperVoiceKeyboard"
export JNI_LIB_DIR="$PROJECT_ROOT/app/src/main/jniLibs"
export JNI_INCLUDE_DIR="$PROJECT_ROOT/app/src/main/jniInclude"
export ANDROID_NDK_API_LEVEL=30
export ANDROID_SDK_VERSION=30
export ANDROID_API_LEVEL=30
export ANDROID_BUILD_TOOLS_VERSION=33.0.1
export ANDROID_NDK_VERSION="25.1.8937393"
export ANDROID_SDK_HOME="$HOME/Android/Sdk"
export ANDROID_HOME="$ANDROID_SDK_HOME/build-tools/$ANDROID_BUILD_TOOLS_VERSION"
export ANDROID_NDK_HOME="$ANDROID_SDK_HOME/ndk/$ANDROID_NDK_VERSION"
export FFMPEG_INCLUDE_DIR_AARCH64_LINUX_ANDROID="$JNI_INCLUDE_DIR/arm64-v8a/"
export FFMPEG_LIB_DIR_AARCH64_LINUX_ANDROID="$JNI_LIB_DIR/arm64-v8a/"

export FFMPEG_INCLUDE_DIR_X86_64_LINUX_ANDROID="$JNI_INCLUDE_DIR/x86_64/"
export FFMPEG_LIB_DIR_X86_64_LINUX_ANDROID="$JNI_LIB_DIR/x86_64/"

export FFMPEG_INCLUDE_DIR_ARMV7_LINUX_ANDROIDEABI="$JNI_INCLUDE_DIR/armeabi-v7a/"
export FFMPEG_LIB_DIR_ARMV7_LINUX_ANDROIDEABI="$JNI_LIB_DIR/armeabi-v7a/"

export FFMPEG_INCLUDE_DIR_I686_LINUX_ANDROID="$JNI_INCLUDE_DIR/x86/"
export FFMPEG_LIB_DIR_I686_LINUX_ANDROID="$JNI_LIB_DIR/x86/"