[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
jni = { version = "0.20.0", features = ["default"]}
jni-sys = { version = "0.3.0" } 
ndk = {version = "0.7.0", features = ["api-level-30", "audio", "media"] }
ndk-sys = "0.4.0"
ndk-context= "0.1.1"
log = "0.4.17"
android_logger = "0.11.1"
anyhow= "1.0.66"
tflitec = { git = "https://github.com/MichaelMcCulloch/tflitec-rs", features = ["xnnpack"], branch = "main"}

[profile.release]
lto = true
strip = true


[lib]
name = "rust"
crate-type = ["cdylib"]


